default_stages: [pre-push]
repos:
  - repo: local
    hooks:
      - id: run-frontend-tests
        name: run all unit tests frontend
        entry: ./scripts/run-frontend-test.sh
        language: system
        verbose: true
        pass_filenames: false # <- prevent looping (ref: https://github.com/pre-commit/pre-commit/issues/1636)
        always_run: true
        fail_fast: true
