apiVersion: v1
kind: Service
metadata:
  name: dev-frontend-demo-feature-toggles
  namespace: default
  labels:
    app: dev-frontend-demo-feature-toggles
spec:
  selector:
    app: dev-frontend-demo-feature-toggles
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  # type: LoadBalancer
